# Makefile
#
# Este archivo automatiza la compilación del proyecto.
# Permite compilar todos los archivos fuente ubicados en la carpeta src/
# y generar un ejecutable del compilador.
#
# También puede incluir reglas para limpiar archivos temporales u objetos
# generados durante la compilación.
